### ISSUE TITLE
JSX/Map Feedback

### ISSUE THREAD

**Issue by AdamBrodzinski** [bryanjos/elixirscript#150]
Hi Bryan! First I just wanted to say thanks for creating this project!

I have a toy/hobby language that is more of a "coffeescript" approach and evolved from an OO Ruby feel to more of an Elixir feel: [RedScript](https://github.com/AdamBrodzinski/RedScript). Anyway I just wanted to reach out and let you know in case it inspires some ideas around JSX. 

Also i've tried out Elixirscript and have some feedback and I thought that might be helpful.

Firstly... it's awesome. However, there are some things that make me put it down for now. The amount of effort and noise doesn't outweigh the rest. Using React and using JS object literals. 

In JS object literals are used instead of tuples to pass data around and it feels really awkward to use hash strings `%{"foo" => "bar}"` instead of `{foo: "bar"}`. Have you thought about adding a new map to ElixirScript that would mimick an object literal? Something like `${foo: "bar"}` eg:

```javascript
opts = ${
  name: "Ted",
  type: "admin",
  public: true,
}
```

Also using React without JSX is very verbose. With the new stateless components it would be really nice to use that. Here's a quick example:

```ruby
defmodule Players do
  # player wrapper
  def PlayerList(props) do
    <div className="players">
      <Player />
    </div>
  end

  def PlayerItem(props) do
    <div>
      <h1>Name: { props.player_name }</h1>
      <input type='button' onClick={ handle_click } />
    </div>
  end

  defp handle_click(e) do
    alert("Hello World")
  end
end
```

Anyway i'm sure you've already thought about these but I mainly just wanted to leave some feedback and to let you know your work is much appreciated!

**Comment by bryanjos** [comment]
Hi Adam! I remember looking at redscript and seeing it again now I'm impressed!

I have thought about both of those points and I agree on both. And on both I'm open to ideas. These, like a lot of other things, I've punted on until there are possibly more contributors and/or people using the project. I just want to minimize making decisions on my own that might end up being bad.

On object literals, it's a bit tough because of keeping compatibility with Elixir. One option could be to come up with a macro (maybe looking like what you suggested) that allows for more natural object literals. I can try some things and see what works.

On JSX, I've thought of a couple of options. One thing the current version of Elixirscript has is an Html module with macros for each html tag that resolve to virtual dom function calls. I've thought about doing something similar for React. I hope to one day break the Html module out of this project into it's own project. The other idea is possibly making a sigil similar to one that exists in Phoenix for doing inline eex templates, but instead would turn into React function calls.

I think the object literal idea that you presented could be something that could be thought about for the version after the upcoming one. The next version should be out soonish. Just trying to get the existing plugins for brunch and webpack up to date and working with the latest version.

**Comment by conradwt** [comment]
@bryanjos I would highly recommend taking a look at Elm (i.e. elm-lang.org) because it has a lot in common with Elixir.  For example, it's both an immutable and functional language for building reactive web sites.  Also, it has a very good compiler and a performs quite for front-end development (i.e. http://elm-lang.org/blog/blazing-fast-html).  Just something to take a look at during the evolution of ElixirScript.

**Comment by bryanjos** [comment]
@conradwt I've pretty familiar with Elm and continue to watch it. I really do like its compiler.

**Comment by AdamBrodzinski** [comment]
@bryanjos cool sounds good! I agree, these things shouldn't be the main focus for now as other issues (IMHO) are more important than sugar. I wish I had the time to help hack on this! :smile: 

Feel free to close this out if it's out of scope.

**Comment by bryanjos** [comment]
@AdamBrodzinski it'll definitely be useful. When I get some time I'm going to try to prototype it and see how it works

**Comment by AdamBrodzinski** [comment]
Nice! feel free to ping me if you need someone to test :+1:

**Comment by bryanjos** [comment]
Closing in favor of #153 and #157
